### ISSUE TITLE
Wrong artifact is injected for Scala.js

### ISSUE THREAD

**Issue by MasseGuillaume** [trueaccord/sbt-scalapb#15] opened 2018-04-15 13:42 UTC
https://github.com/scalapb/sbt-scalapb/blob/98709592ada78dacdfb3caff33cf9284859e02f7/src/main/scala/com/trueaccord/scalapb/ScalaPbPlugin.scala#L82

If you have a Scala.js project it should add

`"com.trueaccord.scalapb" %%% "scalapb-runtime" % runtimeVersion`

**Comment by thesamet** [comment] 2018-04-15 13:49
Thanks for reporting. This is a duplicate of https://github.com/scalapb/ScalaPB/issues/397. Help wanted on this issue.

**Closed as completed by thesamet** 2018-04-15 13:49 UTC
